# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessListMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=255)),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_address', models.CharField(max_length=255)),
                ('bus_phone', models.CharField(max_length=255)),
                ('bus_introduction', models.CharField(max_length=255)),
                ('bus_slogan', models.CharField(max_length=255)),
                ('bus_class', models.CharField(max_length=255)),
                ('bus_characteristic', models.CharField(max_length=255)),
                ('bus_delivery', models.CharField(max_length=255)),
                ('bus_start_delivery', models.CharField(max_length=255)),
                ('bus_start_time', models.CharField(max_length=255)),
                ('bus_end_time', models.CharField(max_length=255)),
                ('bus_avator', models.ImageField(blank=True, max_length=1000, upload_to='bussiness/%Y%m%d/', verbose_name='\u5e97\u94fa\u5934\u50cf')),
                ('bus_permit', models.ImageField(max_length=1000, upload_to='bussiness/%Y-%m-%d/%H-%M-%S/', verbose_name='\u8425\u4e1a\u6267\u7167')),
                ('bus_cater', models.ImageField(max_length=1000, upload_to='bussiness/%Y-%m-%d/%H-%M-%S/', verbose_name='\u9910\u996e\u8bb8\u53ef\u8bc1')),
                ('bus_discount', models.CharField(max_length=255)),
            ],
        ),
    ]
