# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0002_bussinesslistmod_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImageMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(default='', max_length=255)),
                ('bus_name', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to='bussiness')),
            ],
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_avator',
            field=models.FileField(blank=True, max_length=1000, upload_to='bussiness', verbose_name='\u5e97\u94fa\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_cater',
            field=models.FileField(max_length=1000, upload_to='bussiness', verbose_name='\u9910\u996e\u8bb8\u53ef\u8bc1'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_permit',
            field=models.FileField(max_length=1000, upload_to='bussiness', verbose_name='\u8425\u4e1a\u6267\u7167'),
        ),
    ]
