# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0003_auto_20191105_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_avator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_cater',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_permit',
            field=models.CharField(max_length=255),
        ),
    ]
