# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0004_auto_20191105_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessimagemod',
            name='bus_name',
        ),
    ]
