# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0005_remove_businessimagemod_bus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCaterMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to='bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPermitMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to='bussiness')),
            ],
        ),
    ]
