# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0006_businesscatermod_businesspermitmod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessCaterMod',
        ),
        migrations.DeleteModel(
            name='BusinessPermitMod',
        ),
    ]
