# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0007_auto_20191106_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessimagemod',
            name='file',
            field=models.ImageField(upload_to='bussiness'),
        ),
    ]
