# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0008_auto_20191107_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussinesslistmod',
            old_name='uid',
            new_name='sid',
        ),
    ]
