# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0009_auto_20191107_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessimagemod',
            options={'verbose_name': '\u5e97\u94fa\u56fe\u7247', 'verbose_name_plural': '\u5e97\u94fa\u56fe\u7247'},
        ),
        migrations.AlterModelOptions(
            name='bussinesslistmod',
            options={'verbose_name': '\u5e97\u94fa\u4fe1\u606f', 'verbose_name_plural': '\u5e97\u94fa\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='businessimagemod',
            name='bid',
            field=models.CharField(default='', max_length=255, verbose_name='\u5e97\u94faid'),
        ),
        migrations.AlterField(
            model_name='businessimagemod',
            name='file',
            field=models.ImageField(upload_to='media/bussiness', verbose_name='\u5e97\u94fa\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bid',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94faid'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_address',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_avator',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_cater',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u8425\u4e1a\u6267\u7167'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_characteristic',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u7279\u5f81'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_class',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_delivery',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u914d\u9001'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_discount',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u6d3b\u52a8'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_end_time',
            field=models.CharField(max_length=255, verbose_name='\u95ed\u5e97\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_introduction',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_name',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_permit',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u8bb8\u53ef\u8bc1'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_phone',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_slogan',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u6807\u8bed'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_start_delivery',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94fa\u914d\u9001\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='bus_start_time',
            field=models.CharField(max_length=255, verbose_name='\u5f00\u5e97\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='bussinesslistmod',
            name='sid',
            field=models.CharField(default='', max_length=255, verbose_name='\u5546\u5bb6id'),
        ),
    ]
