# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0002_orderlistmod_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlistmod',
            name='order_receive_address',
        ),
    ]
