# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0003_remove_orderlistmod_order_receive_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlistmod',
            options={'verbose_name': '\u8ba2\u5355\u4fe1\u606f', 'verbose_name_plural': '\u8ba2\u5355\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='orderlistmod',
            name='bid',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94faid'),
        ),
        migrations.AlterField(
            model_name='orderlistmod',
            name='oid',
            field=models.CharField(max_length=255, verbose_name='\u8ba2\u5355id'),
        ),
        migrations.AlterField(
            model_name='orderlistmod',
            name='order_allprice',
            field=models.CharField(max_length=255, verbose_name='\u8ba2\u5355\u603b\u4ef7'),
        ),
        migrations.AlterField(
            model_name='orderlistmod',
            name='order_name',
            field=models.CharField(max_length=255, verbose_name='\u8ba2\u5355\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='orderlistmod',
            name='order_status',
            field=models.CharField(max_length=255, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='orderlistmod',
            name='uid',
            field=models.CharField(default='', max_length=255, verbose_name='\u7528\u6237id'),
        ),
    ]
