# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0002_userlistmod_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlistmod',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='userlistmod',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userlistmod',
            old_name='pwd',
            new_name='user_pwd',
        ),
        migrations.RenameField(
            model_name='userlistmod',
            old_name='time',
            new_name='user_time',
        ),
    ]
