# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0004_userwarnmod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlistmod',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='userwarnmod',
            options={'verbose_name': '\u7528\u6237\u9884\u8b66', 'verbose_name_plural': '\u7528\u6237\u9884\u8b66'},
        ),
        migrations.AlterField(
            model_name='userlistmod',
            name='uid',
            field=models.CharField(max_length=255, verbose_name='\u7528\u6237id'),
        ),
        migrations.AlterField(
            model_name='userlistmod',
            name='user_address',
            field=models.CharField(max_length=255, verbose_name='\u7528\u6237\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='userlistmod',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='\u7528\u6237\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='userlistmod',
            name='user_pwd',
            field=models.CharField(default='', max_length=255, verbose_name='\u7528\u6237\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='userlistmod',
            name='user_time',
            field=models.CharField(max_length=255, verbose_name='\u7528\u6237\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userwarnmod',
            name='uid',
            field=models.CharField(max_length=255, verbose_name='\u7528\u6237id'),
        ),
        migrations.AlterField(
            model_name='userwarnmod',
            name='user_content',
            field=models.CharField(max_length=255, verbose_name='\u7528\u6237\u9884\u8b66'),
        ),
    ]
