# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminListMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_registertime', models.CharField(max_length=255)),
                ('admin_address', models.CharField(max_length=255)),
                ('admin_authority', models.IntegerField(max_length=255)),
                ('admin_avator', models.ImageField(blank=True, max_length=1000, upload_to='admin/%Y%m%d/', verbose_name='\u7ba1\u7406\u5458\u5934\u50cf')),
            ],
        ),
    ]
