# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_list', '0002_adminlistmod_admin_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_avator',
            field=models.FileField(blank=True, max_length=1000, upload_to='%Y%m%d', verbose_name='\u7ba1\u7406\u5458\u5934\u50cf'),
        ),
    ]
