# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_list', '0003_auto_20191105_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminImageMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%Y%m%d')),
            ],
        ),
    ]
