# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_list', '0005_auto_20191105_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminimagemod',
            name='aid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminimagemod',
            name='file',
            field=models.FileField(upload_to='admin'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_avator',
            field=models.FileField(blank=True, max_length=1000, upload_to='admin', verbose_name='\u7ba1\u7406\u5458\u5934\u50cf'),
        ),
    ]
