# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_list', '0007_auto_20191106_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminimagemod',
            options={'verbose_name': '\u7ba1\u7406\u5458\u56fe\u7247', 'verbose_name_plural': '\u7ba1\u7406\u5458\u56fe\u7247'},
        ),
        migrations.AlterModelOptions(
            name='adminlistmod',
            options={'verbose_name': '\u7ba1\u7406\u5458\u4fe1\u606f', 'verbose_name_plural': '\u7ba1\u7406\u5458\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='adminimagemod',
            name='aid',
            field=models.CharField(default='', max_length=255, verbose_name='\u7ba1\u7406\u5458id'),
        ),
        migrations.AlterField(
            model_name='adminimagemod',
            name='file',
            field=models.FileField(upload_to='media/admin', verbose_name='\u7ba1\u7406\u5458\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_address',
            field=models.CharField(max_length=255, verbose_name='\u7ba1\u7406\u5458\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_authority',
            field=models.IntegerField(max_length=255, verbose_name='\u7ba1\u7406\u5458\u6743\u9650'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_avator',
            field=models.CharField(max_length=255, verbose_name='\u7ba1\u7406\u5458\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_name',
            field=models.CharField(max_length=255, verbose_name='\u7ba1\u7406\u5458\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_pwd',
            field=models.CharField(default='', max_length=255, verbose_name='\u7ba1\u7406\u5458\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='admin_registertime',
            field=models.CharField(max_length=255, verbose_name='\u7ba1\u7406\u5458\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='adminlistmod',
            name='aid',
            field=models.CharField(max_length=255, verbose_name='\u7ba1\u7406\u5458id'),
        ),
    ]
