# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BussCommentListMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=255)),
                ('bus_score', models.CharField(max_length=255)),
                ('bus_sell', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCommentListMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=255)),
                ('bus_score', models.CharField(max_length=255)),
                ('bus_sell', models.IntegerField(max_length=255)),
            ],
        ),
    ]
