# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_list', '0002_auto_20191104_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busscommentlistmod',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='foodcommentlistmod',
            name='uid',
        ),
    ]
