# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_list', '0003_auto_20191104_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='busscommentlistmod',
            name='uid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodcommentlistmod',
            name='uid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
