# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_list', '0004_auto_20191105_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcommentlistmod',
            old_name='bus_score',
            new_name='food_score',
        ),
        migrations.RenameField(
            model_name='foodcommentlistmod',
            old_name='bus_sell',
            new_name='food_sell',
        ),
    ]
