# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_list', '0005_auto_20191106_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcommentlistmod',
            name='bid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
