# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_list', '0007_auto_20191107_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busscommentlistmod',
            options={'verbose_name': '\u5e97\u94fa\u5176\u4ed6\u4fe1\u606f', 'verbose_name_plural': '\u5e97\u94fa\u5176\u4ed6\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='foodcommentlistmod',
            options={'verbose_name': '\u98df\u54c1\u5176\u4ed6\u4fe1\u606f', 'verbose_name_plural': '\u98df\u54c1\u5176\u4ed6\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='busscommentlistmod',
            name='bid',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94faid'),
        ),
        migrations.AlterField(
            model_name='busscommentlistmod',
            name='bus_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='\u5e97\u94fa\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='busscommentlistmod',
            name='bus_sell',
            field=models.IntegerField(max_length=255, verbose_name='\u5e97\u94fa\u9500\u91cf'),
        ),
        migrations.AlterField(
            model_name='foodcommentlistmod',
            name='fid',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1id'),
        ),
        migrations.AlterField(
            model_name='foodcommentlistmod',
            name='food_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='\u5546\u54c1\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='foodcommentlistmod',
            name='food_sell',
            field=models.IntegerField(max_length=255, verbose_name='\u5546\u54c1\u9500\u91cf'),
        ),
    ]
