# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreListMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255)),
                ('bid_list', models.CharField(max_length=255)),
                ('store_time', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('store_pwd', models.CharField(default='', max_length=255)),
                ('store_address', models.CharField(max_length=255)),
            ],
        ),
    ]
