# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storelistmod',
            old_name='bid_list',
            new_name='bid',
        ),
    ]
