# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_list', '0002_auto_20191108_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWarnMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255)),
                ('store_content', models.CharField(max_length=255)),
            ],
        ),
    ]
