# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_list', '0003_storewarnmod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storelistmod',
            options={'verbose_name': '\u5546\u5bb6\u4fe1\u606f', 'verbose_name_plural': '\u5546\u5bb6\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='storewarnmod',
            options={'verbose_name': '\u5546\u5bb6\u9884\u8b66', 'verbose_name_plural': '\u5546\u5bb6\u9884\u8b66'},
        ),
        migrations.AlterField(
            model_name='storelistmod',
            name='bid',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94faid'),
        ),
        migrations.AlterField(
            model_name='storelistmod',
            name='sid',
            field=models.CharField(max_length=255, verbose_name='\u5546\u5bb6id'),
        ),
        migrations.AlterField(
            model_name='storelistmod',
            name='store_address',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='storelistmod',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='storelistmod',
            name='store_pwd',
            field=models.CharField(default='', max_length=255, verbose_name='\u5546\u54c1\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='storelistmod',
            name='store_time',
            field=models.CharField(max_length=255, verbose_name='\u5546\u5bb6\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='storewarnmod',
            name='sid',
            field=models.CharField(max_length=255, verbose_name='\u5546\u5bb6id'),
        ),
        migrations.AlterField(
            model_name='storewarnmod',
            name='store_content',
            field=models.CharField(max_length=255, verbose_name='\u5546\u5bb6\u9884\u8b66'),
        ),
    ]
