# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=255)),
                ('bid', models.CharField(max_length=255)),
                ('food_name', models.CharField(max_length=255)),
                ('food_activity', models.CharField(max_length=255)),
                ('food_introduction', models.CharField(max_length=255)),
                ('food_class', models.CharField(max_length=255)),
                ('food_class_detail', models.CharField(max_length=255)),
                ('food_other', models.CharField(max_length=255)),
                ('food_avator', models.ImageField(blank=True, max_length=1000, upload_to='food/%Y%m%d/', verbose_name='\u98df\u54c1\u5934\u50cf')),
            ],
        ),
    ]
