# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0002_foodlistmod_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImageMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to='food')),
            ],
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_avator',
            field=models.CharField(max_length=255),
        ),
    ]
