# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0003_auto_20191106_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlistmod',
            name='uid',
        ),
    ]
