# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0004_remove_foodlistmod_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlistmod',
            name='food_characteristic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
