# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0005_foodlistmod_food_characteristic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodimagemod',
            options={'verbose_name': '\u5546\u54c1\u56fe\u7247', 'verbose_name_plural': '\u5546\u54c1\u56fe\u7247'},
        ),
        migrations.AlterModelOptions(
            name='foodlistmod',
            options={'verbose_name': '\u5546\u54c1\u4fe1\u606f', 'verbose_name_plural': '\u5546\u54c1\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='foodimagemod',
            name='fid',
            field=models.CharField(default='', max_length=255, verbose_name='\u5546\u54c1id'),
        ),
        migrations.AlterField(
            model_name='foodimagemod',
            name='file',
            field=models.FileField(upload_to='media/food', verbose_name='\u5546\u54c1\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='bid',
            field=models.CharField(max_length=255, verbose_name='\u5e97\u94faid'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='fid',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1id'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_activity',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u6d3b\u52a8'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_avator',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_characteristic',
            field=models.CharField(default='', max_length=255, verbose_name='\u5546\u54c1\u7279\u5f81'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_class',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_class_detail',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u5206\u7c7b\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_introduction',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_name',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='foodlistmod',
            name='food_other',
            field=models.CharField(max_length=255, verbose_name='\u5546\u54c1\u89c4\u683c'),
        ),
    ]
